import type {
  DeleteResultRecord,
  MemoSummaryRecord,
  PaginatedResult,
  PaginationInput,
} from "@/modules/company/application/ports/company.repository";

export type {
  DeleteResultRecord,
  PaginatedResult,
  PaginationInput,
} from "@/modules/company/application/ports/company.repository";

export const DEAL_REPOSITORY = Symbol("DEAL_REPOSITORY");

export type DealStage = "INITIAL_CONTACT" | "IN_DISCUSSION" | "WON" | "LOST";

export type DealLikelihoodStatus = "POSITIVE" | "NEUTRAL" | "NEGATIVE";

export type NextActionStatus =
  | "NONE"
  | "SCHEDULED"
  | "DUE_SOON"
  | "OVERDUE"
  | "DONE";

export interface DealRecord {
  readonly id: string;
  readonly userId: string;
  readonly title: string;
  readonly companyId: string | null;
  readonly companyName: string | null;
  readonly contactId: string | null;
  readonly contactName: string | null;
  readonly amount: number;
  readonly currency: string;
  readonly stage: DealStage;
  readonly likelihoodStatus: DealLikelihoodStatus;
  readonly likelihoodPercent: number | null;
  readonly expectedCloseDate: Date | null;
  readonly nextActionText: string | null;
  readonly nextActionDueAt: Date | null;
  readonly nextActionStatus: NextActionStatus;
  readonly memoSummary: MemoSummaryRecord;
  readonly createdAt: Date;
  readonly updatedAt: Date;
  readonly deletedAt: Date | null;
  readonly permanentDeleteAt: Date | null;
}

export interface DealProductRecord {
  readonly id: string;
  readonly name: string;
  readonly category: string | null;
  readonly unitPrice: number | null;
  readonly currency: string;
  readonly description: string | null;
  readonly connectionCount: number;
  readonly memoSummary: MemoSummaryRecord;
  readonly createdAt: Date;
  readonly updatedAt: Date;
  readonly deletedAt: Date | null;
  readonly permanentDeleteAt: Date | null;
}

export interface DealActivityRecord {
  readonly id: string;
  readonly dealId: string;
  readonly typeId: string;
  readonly typeName: string;
  readonly occurredAt: Date;
  readonly title: string;
  readonly content: string | null;
  readonly isAutoGenerated: boolean;
  readonly createdAt: Date;
  readonly updatedAt: Date;
  readonly deletedAt: Date | null;
  readonly permanentDeleteAt: Date | null;
}

export interface DealMemoRecord {
  readonly id: string;
  readonly targetType: "DEAL";
  readonly targetId: string;
  readonly memoDate: Date;
  readonly title: string | null;
  readonly content: string;
  readonly createdAt: Date;
  readonly updatedAt: Date;
  readonly deletedAt: Date | null;
  readonly permanentDeleteAt: Date | null;
}

export interface DealStageSummaryRecord {
  readonly INITIAL_CONTACT: number;
  readonly IN_DISCUSSION: number;
  readonly WON: number;
  readonly LOST: number;
}

export interface DealSchedulesSummaryRecord {
  readonly totalCount: number;
  readonly upcomingCount: number;
}

export interface DealMeetingNotesSummaryRecord {
  readonly totalCount: number;
  readonly latestMeetingAt: Date | null;
}

export interface DealDetailRecord {
  readonly deal: DealRecord;
  readonly products: DealProductRecord[];
  readonly activities: DealActivityRecord[];
  readonly memos: DealMemoRecord[];
  readonly schedulesSummary: DealSchedulesSummaryRecord;
  readonly meetingNotesSummary: DealMeetingNotesSummaryRecord;
}

export interface DealListResult extends PaginatedResult<DealRecord> {
  readonly stageSummary: DealStageSummaryRecord;
}

export interface ListDealsInput extends PaginationInput {
  readonly userId: string;
  readonly stage: DealStage | null;
  readonly likelihoodStatus: DealLikelihoodStatus | null;
  readonly companyId: string | null;
  readonly contactId: string | null;
  readonly search: string | null;
  readonly nextActionStatus: NextActionStatus | null;
  readonly includeDeleted: boolean;
}

export interface CreateDealInput {
  readonly userId: string;
  readonly title: string;
  readonly companyId: string | null;
  readonly contactId: string | null;
  readonly amount: number;
  readonly currency: string;
  readonly stage: DealStage;
  readonly likelihoodStatus: DealLikelihoodStatus;
  readonly likelihoodPercent: number | null;
  readonly expectedCloseDate: Date | null;
  readonly nextActionText: string | null;
  readonly nextActionDueAt: Date | null;
  readonly productIds: string[];
  readonly initialMemo: string | null;
}

export interface UpdateDealInput {
  readonly userId: string;
  readonly dealId: string;
  readonly title?: string;
  readonly companyId?: string | null;
  readonly contactId?: string | null;
  readonly amount?: number;
  readonly currency?: string;
  readonly stage?: DealStage;
  readonly likelihoodStatus?: DealLikelihoodStatus;
  readonly likelihoodPercent?: number | null;
  readonly expectedCloseDate?: Date | null;
  readonly nextActionText?: string | null;
  readonly nextActionDueAt?: Date | null;
  readonly nextActionStatus?: NextActionStatus;
  readonly productIds?: string[];
}

export interface ChangeDealStageInput {
  readonly userId: string;
  readonly dealId: string;
  readonly stage: DealStage;
  readonly activityTitle: string | null;
  readonly activityContent: string | null;
  readonly occurredAt: Date;
}

export interface UpdateDealNextActionInput {
  readonly userId: string;
  readonly dealId: string;
  readonly nextActionText?: string | null;
  readonly nextActionDueAt?: Date | null;
  readonly nextActionStatus?: NextActionStatus;
}

export interface CompleteDealNextActionInput {
  readonly userId: string;
  readonly dealId: string;
  readonly completedAt: Date;
  readonly activityContent: string | null;
}

export interface SnoozeDealNextActionInput {
  readonly userId: string;
  readonly dealId: string;
  readonly nextActionDueAt: Date;
  readonly reason: string | null;
}

export interface ListDealActivitiesInput extends PaginationInput {
  readonly userId: string;
  readonly dealId: string;
}

export interface CreateDealActivityInput {
  readonly userId: string;
  readonly dealId: string;
  readonly typeId: string;
  readonly occurredAt: Date;
  readonly title: string;
  readonly content: string | null;
}

export interface UpdateDealActivityInput {
  readonly userId: string;
  readonly dealId: string;
  readonly activityId: string;
  readonly typeId?: string;
  readonly occurredAt?: Date;
  readonly title?: string;
  readonly content?: string | null;
}

export interface DealRepository {
  listDeals(input: ListDealsInput): Promise<DealListResult>;
  createDeal(input: CreateDealInput): Promise<DealRecord>;
  getDealDetail(
    userId: string,
    dealId: string
  ): Promise<DealDetailRecord | null>;
  updateDeal(input: UpdateDealInput): Promise<DealRecord>;
  changeDealStage(input: ChangeDealStageInput): Promise<DealRecord>;
  updateDealNextAction(input: UpdateDealNextActionInput): Promise<DealRecord>;
  completeDealNextAction(input: CompleteDealNextActionInput): Promise<DealRecord>;
  snoozeDealNextAction(input: SnoozeDealNextActionInput): Promise<DealRecord>;
  deleteDeal(
    userId: string,
    dealId: string,
    now: Date,
    permanentDeleteAt: Date
  ): Promise<DeleteResultRecord>;
  restoreDeal(userId: string, dealId: string): Promise<DealRecord>;
  listDealActivities(
    input: ListDealActivitiesInput
  ): Promise<PaginatedResult<DealActivityRecord>>;
  createDealActivity(
    input: CreateDealActivityInput
  ): Promise<DealActivityRecord>;
  updateDealActivity(
    input: UpdateDealActivityInput
  ): Promise<DealActivityRecord>;
  deleteDealActivity(
    userId: string,
    dealId: string,
    activityId: string,
    now: Date,
    permanentDeleteAt: Date
  ): Promise<DeleteResultRecord>;
}
