import type {
  DealActivityRecord,
  DealDetailRecord,
  DealListResult,
  DealMeetingNotesSummaryRecord,
  DealMemoRecord,
  DealProductRecord,
  DealRecord,
  DealSchedulesSummaryRecord,
  DealStageSummaryRecord,
  DeleteResultRecord,
  PaginatedResult,
} from "@/modules/deal/application/ports/deal.repository";

export interface DealResponse {
  readonly id: string;
  readonly title: string;
  readonly companyId: string | null;
  readonly companyName: string | null;
  readonly contactId: string | null;
  readonly contactName: string | null;
  readonly amount: number;
  readonly currency: string;
  readonly stage: string;
  readonly likelihoodStatus: string;
  readonly likelihoodPercent: number | null;
  readonly expectedCloseDate: string | null;
  readonly nextActionText: string | null;
  readonly nextActionDueAt: string | null;
  readonly nextActionStatus: string;
  readonly hasMemo: boolean;
  readonly memoCount: number;
  readonly latestMemoAt: string | null;
  readonly createdAt: string;
  readonly updatedAt: string;
  readonly deletedAt: string | null;
  readonly permanentDeleteAt: string | null;
}

export interface DealProductResponse {
  readonly id: string;
  readonly name: string;
  readonly category: string | null;
  readonly unitPrice: number | null;
  readonly currency: string;
  readonly description: string | null;
  readonly connectionCount: number;
  readonly hasMemo: boolean;
  readonly memoCount: number;
  readonly latestMemoAt: string | null;
  readonly createdAt: string;
  readonly updatedAt: string;
  readonly deletedAt: string | null;
  readonly permanentDeleteAt: string | null;
}

export interface DealActivityResponse {
  readonly id: string;
  readonly dealId: string;
  readonly typeId: string;
  readonly typeName: string;
  readonly occurredAt: string;
  readonly title: string;
  readonly content: string | null;
  readonly isAutoGenerated: boolean;
  readonly createdAt: string;
  readonly updatedAt: string;
  readonly deletedAt: string | null;
  readonly permanentDeleteAt: string | null;
}

export interface DealMemoResponse {
  readonly id: string;
  readonly targetType: "DEAL";
  readonly targetId: string;
  readonly memoDate: string;
  readonly title: string | null;
  readonly content: string;
  readonly createdAt: string;
  readonly updatedAt: string;
  readonly deletedAt: string | null;
  readonly permanentDeleteAt: string | null;
}

export interface DealDetailResponse {
  readonly deal: DealResponse;
  readonly products: DealProductResponse[];
  readonly activities: DealActivityResponse[];
  readonly memos: DealMemoResponse[];
  readonly schedulesSummary: DealSchedulesSummaryRecord;
  readonly meetingNotesSummary: DealMeetingNotesSummaryResponse;
}

export interface DealMeetingNotesSummaryResponse {
  readonly totalCount: number;
  readonly latestMeetingAt: string | null;
}

export interface DealListResponse {
  readonly items: DealResponse[];
  readonly stageSummary: DealStageSummaryRecord;
  readonly page: number;
  readonly pageSize: number;
  readonly totalCount: number;
  readonly hasNext: boolean;
}

export interface PaginatedResponse<TItem> {
  readonly items: TItem[];
  readonly page: number;
  readonly pageSize: number;
  readonly totalCount: number;
  readonly hasNext: boolean;
}

export interface DeleteResponse {
  readonly id: string;
  readonly deletedAt: string;
  readonly permanentDeleteAt: string;
}

export function toDealResponse(deal: DealRecord): DealResponse {
  return {
    id: deal.id,
    title: deal.title,
    companyId: deal.companyId,
    companyName: deal.companyName,
    contactId: deal.contactId,
    contactName: deal.contactName,
    amount: deal.amount,
    currency: deal.currency,
    stage: deal.stage,
    likelihoodStatus: deal.likelihoodStatus,
    likelihoodPercent: deal.likelihoodPercent,
    expectedCloseDate: toIsoOrNull(deal.expectedCloseDate),
    nextActionText: deal.nextActionText,
    nextActionDueAt: toIsoOrNull(deal.nextActionDueAt),
    nextActionStatus: deal.nextActionStatus,
    hasMemo: deal.memoSummary.hasMemo,
    memoCount: deal.memoSummary.memoCount,
    latestMemoAt: toIsoOrNull(deal.memoSummary.latestMemoAt),
    createdAt: deal.createdAt.toISOString(),
    updatedAt: deal.updatedAt.toISOString(),
    deletedAt: toIsoOrNull(deal.deletedAt),
    permanentDeleteAt: toIsoOrNull(deal.permanentDeleteAt),
  };
}

export function toDealProductResponse(
  product: DealProductRecord
): DealProductResponse {
  return {
    id: product.id,
    name: product.name,
    category: product.category,
    unitPrice: product.unitPrice,
    currency: product.currency,
    description: product.description,
    connectionCount: product.connectionCount,
    hasMemo: product.memoSummary.hasMemo,
    memoCount: product.memoSummary.memoCount,
    latestMemoAt: toIsoOrNull(product.memoSummary.latestMemoAt),
    createdAt: product.createdAt.toISOString(),
    updatedAt: product.updatedAt.toISOString(),
    deletedAt: toIsoOrNull(product.deletedAt),
    permanentDeleteAt: toIsoOrNull(product.permanentDeleteAt),
  };
}

export function toDealActivityResponse(
  activity: DealActivityRecord
): DealActivityResponse {
  return {
    id: activity.id,
    dealId: activity.dealId,
    typeId: activity.typeId,
    typeName: activity.typeName,
    occurredAt: activity.occurredAt.toISOString(),
    title: activity.title,
    content: activity.content,
    isAutoGenerated: activity.isAutoGenerated,
    createdAt: activity.createdAt.toISOString(),
    updatedAt: activity.updatedAt.toISOString(),
    deletedAt: toIsoOrNull(activity.deletedAt),
    permanentDeleteAt: toIsoOrNull(activity.permanentDeleteAt),
  };
}

export function toDealMemoResponse(memo: DealMemoRecord): DealMemoResponse {
  return {
    id: memo.id,
    targetType: memo.targetType,
    targetId: memo.targetId,
    memoDate: memo.memoDate.toISOString(),
    title: memo.title,
    content: memo.content,
    createdAt: memo.createdAt.toISOString(),
    updatedAt: memo.updatedAt.toISOString(),
    deletedAt: toIsoOrNull(memo.deletedAt),
    permanentDeleteAt: toIsoOrNull(memo.permanentDeleteAt),
  };
}

export function toDealDetailResponse(
  detail: DealDetailRecord
): DealDetailResponse {
  return {
    deal: toDealResponse(detail.deal),
    products: detail.products.map(toDealProductResponse),
    activities: detail.activities.map(toDealActivityResponse),
    memos: detail.memos.map(toDealMemoResponse),
    schedulesSummary: detail.schedulesSummary,
    meetingNotesSummary: toDealMeetingNotesSummaryResponse(
      detail.meetingNotesSummary
    ),
  };
}

export function toDealListResponse(result: DealListResult): DealListResponse {
  return {
    items: result.items.map(toDealResponse),
    stageSummary: result.stageSummary,
    page: result.page,
    pageSize: result.pageSize,
    totalCount: result.totalCount,
    hasNext: result.hasNext,
  };
}

export function toPaginatedResponse<TInput, TOutput>(
  result: PaginatedResult<TInput>,
  mapItem: (item: TInput) => TOutput
): PaginatedResponse<TOutput> {
  return {
    items: result.items.map(mapItem),
    page: result.page,
    pageSize: result.pageSize,
    totalCount: result.totalCount,
    hasNext: result.hasNext,
  };
}

export function toDeleteResponse(result: DeleteResultRecord): DeleteResponse {
  return {
    id: result.id,
    deletedAt: result.deletedAt.toISOString(),
    permanentDeleteAt: result.permanentDeleteAt.toISOString(),
  };
}

function toDealMeetingNotesSummaryResponse(
  summary: DealMeetingNotesSummaryRecord
): DealMeetingNotesSummaryResponse {
  return {
    totalCount: summary.totalCount,
    latestMeetingAt: toIsoOrNull(summary.latestMeetingAt),
  };
}

function toIsoOrNull(date: Date | null): string | null {
  return date ? date.toISOString() : null;
}
