import type { PaginatedResponse } from "@/types/pagination";

export type DealStage =
  | "INITIAL_CONTACT"
  | "NEEDS_ANALYSIS"
  | "PROPOSAL"
  | "NEGOTIATION"
  | "WON"
  | "LOST";

export type DealLikelihoodStatus = "POSITIVE" | "NEUTRAL" | "NEGATIVE";

export type NextActionStatus =
  | "NONE"
  | "SCHEDULED"
  | "DUE_SOON"
  | "OVERDUE"
  | "DONE";

export type Deal = {
  readonly id: string;
  readonly title: string;
  readonly companyId: string | null;
  readonly companyName: string | null;
  readonly contactId: string | null;
  readonly contactName: string | null;
  readonly amount: number;
  readonly currency: string;
  readonly stage: DealStage;
  readonly likelihoodStatus: DealLikelihoodStatus;
  readonly likelihoodPercent: number | null;
  readonly expectedCloseDate: string | null;
  readonly nextActionText: string | null;
  readonly nextActionDueAt: string | null;
  readonly nextActionStatus: NextActionStatus;
  readonly hasMemo: boolean;
  readonly memoCount: number;
  readonly latestMemoAt: string | null;
  readonly createdAt: string;
  readonly updatedAt: string;
  readonly deletedAt: string | null;
  readonly permanentDeleteAt: string | null;
};

export type DealProduct = {
  readonly id: string;
  readonly name: string;
  readonly category: string | null;
  readonly unitPrice: number | null;
  readonly currency: string;
  readonly description: string | null;
  readonly connectionCount: number;
  readonly hasMemo: boolean;
  readonly memoCount: number;
  readonly latestMemoAt: string | null;
  readonly createdAt: string;
  readonly updatedAt: string;
  readonly deletedAt: string | null;
  readonly permanentDeleteAt: string | null;
};

export type DealActivity = {
  readonly id: string;
  readonly dealId: string;
  readonly typeId: string;
  readonly typeName: string;
  readonly occurredAt: string;
  readonly title: string;
  readonly content: string | null;
  readonly isAutoGenerated: boolean;
  readonly createdAt: string;
  readonly updatedAt: string;
  readonly deletedAt: string | null;
  readonly permanentDeleteAt: string | null;
};

export type DealMemo = {
  readonly id: string;
  readonly targetType: "DEAL";
  readonly targetId: string;
  readonly memoDate: string;
  readonly title: string | null;
  readonly content: string;
  readonly createdAt: string;
  readonly updatedAt: string;
  readonly deletedAt: string | null;
  readonly permanentDeleteAt: string | null;
};

export type DealSchedulesSummary = {
  readonly totalCount: number;
  readonly upcomingCount: number;
};

export type DealMeetingNotesSummary = {
  readonly totalCount: number;
  readonly latestMeetingAt: string | null;
};

export type DealDetail = {
  readonly deal: Deal;
  readonly products: DealProduct[];
  readonly activities: DealActivity[];
  readonly memos: DealMemo[];
  readonly schedulesSummary: DealSchedulesSummary;
  readonly meetingNotesSummary: DealMeetingNotesSummary;
};

export type DealStageSummary = Partial<Record<DealStage, number>>;

export type DealListResponse = PaginatedResponse<Deal> & {
  readonly stageSummary: DealStageSummary;
};

export type DealActivityListResponse = PaginatedResponse<DealActivity>;

export type DealListParams = {
  readonly page?: number;
  readonly pageSize?: number;
  readonly search?: string;
  readonly stage?: DealStage;
  readonly likelihoodStatus?: DealLikelihoodStatus;
  readonly nextActionStatus?: NextActionStatus;
  readonly companyId?: string;
  readonly contactId?: string;
  readonly includeDeleted?: boolean;
};

export type CreateDealInput = {
  readonly title: string;
  readonly companyId?: string;
  readonly contactId?: string;
  readonly amount: number;
  readonly currency?: string;
  readonly stage?: DealStage;
  readonly likelihoodStatus?: DealLikelihoodStatus;
  readonly likelihoodPercent?: number;
  readonly expectedCloseDate?: string;
  readonly nextActionText?: string;
  readonly nextActionDueAt?: string;
  readonly productIds?: string[];
  readonly initialMemo?: string;
};

export type ChangeDealStageInput = {
  readonly dealId: string;
  readonly stage: DealStage;
  readonly activityTitle?: string;
  readonly activityContent?: string;
};

export type UpdateDealNextActionInput = {
  readonly dealId: string;
  readonly nextActionText?: string | null;
  readonly nextActionDueAt?: string | null;
  readonly nextActionStatus?: NextActionStatus;
};

export type CompleteDealNextActionInput = {
  readonly dealId: string;
  readonly completedAt?: string;
  readonly activityContent?: string;
};

export type SnoozeDealNextActionInput = {
  readonly dealId: string;
  readonly nextActionDueAt: string;
  readonly reason?: string;
};

export type DealActivityListParams = {
  readonly page?: number;
  readonly pageSize?: number;
};

export type CreateDealActivityInput = {
  readonly dealId: string;
  readonly typeId?: string;
  readonly occurredAt: string;
  readonly title: string;
  readonly content?: string;
};
