import { expect, test, type Page, type Route } from "@playwright/test";

const COMPANY_NAME = "스모크상사";
const CONTACT_NAME = "김스모크";
const PRODUCT_NAME = "MVP 패키지";
const DEAL_TITLE = "스모크 MVP 딜";
const SCHEDULE_TITLE = "스모크 미팅 일정";
const MEETING_DETAILS = "MVP 도입 일정과 검토 범위를 합의했다.";
const MOCK_ACCESS_TOKEN = "Bearer mock-user-web-access-token";

type DealStage = "INITIAL_CONTACT" | "IN_DISCUSSION" | "WON" | "LOST";
type DealLikelihoodStatus = "POSITIVE" | "NEUTRAL" | "NEGATIVE";
type NextActionStatus = "NONE" | "SCHEDULED" | "DUE_SOON" | "OVERDUE" | "DONE";

type Company = {
  readonly id: string;
  readonly name: string;
  readonly industry: string | null;
  readonly region: string | null;
  readonly address: string | null;
  readonly website: string | null;
  readonly description: string | null;
  readonly tags: readonly { readonly id: string; readonly name: string; readonly color: string | null }[];
  readonly hasMemo: boolean;
  readonly memoCount: number;
  readonly latestMemoAt: string | null;
  readonly contactCount: number;
  readonly dealCount: number;
  readonly productCount: number;
  readonly createdAt: string;
  readonly updatedAt: string;
  readonly deletedAt: string | null;
  readonly permanentDeleteAt: string | null;
};

type Contact = {
  readonly id: string;
  readonly name: string;
  readonly companyId: string | null;
  readonly companyName: string | null;
  readonly department: string | null;
  readonly position: string | null;
  readonly phone: string | null;
  readonly email: string | null;
  readonly address: string | null;
  readonly hasMemo: boolean;
  readonly memoCount: number;
  readonly latestMemoAt: string | null;
  readonly createdAt: string;
  readonly updatedAt: string;
  readonly deletedAt: string | null;
  readonly permanentDeleteAt: string | null;
};

type Product = {
  readonly id: string;
  readonly name: string;
  readonly category: string | null;
  readonly unitPrice: number | null;
  readonly currency: string;
  readonly description: string | null;
  readonly connectionCount: number;
  readonly hasMemo: boolean;
  readonly memoCount: number;
  readonly latestMemoAt: string | null;
  readonly createdAt: string;
  readonly updatedAt: string;
  readonly deletedAt: string | null;
  readonly permanentDeleteAt: string | null;
};

type Deal = {
  readonly id: string;
  readonly title: string;
  readonly companyId: string | null;
  readonly companyName: string | null;
  readonly contactId: string | null;
  readonly contactName: string | null;
  readonly amount: number;
  readonly currency: string;
  readonly stage: DealStage;
  readonly likelihoodStatus: DealLikelihoodStatus;
  readonly likelihoodPercent: number | null;
  readonly expectedCloseDate: string | null;
  readonly nextActionText: string | null;
  readonly nextActionDueAt: string | null;
  readonly nextActionStatus: NextActionStatus;
  readonly hasMemo: boolean;
  readonly memoCount: number;
  readonly latestMemoAt: string | null;
  readonly createdAt: string;
  readonly updatedAt: string;
  readonly deletedAt: string | null;
  readonly permanentDeleteAt: string | null;
};

type DealActivity = {
  readonly id: string;
  readonly dealId: string;
  readonly typeId: string;
  readonly typeName: string;
  readonly occurredAt: string;
  readonly title: string;
  readonly content: string | null;
  readonly isAutoGenerated: boolean;
  readonly createdAt: string;
  readonly updatedAt: string;
  readonly deletedAt: string | null;
  readonly permanentDeleteAt: string | null;
};

type Schedule = {
  readonly id: string;
  readonly title: string;
  readonly startAt: string;
  readonly endAt: string;
  readonly allDay: boolean;
  readonly location: string | null;
  readonly memo: string | null;
  readonly source: "INTERNAL" | "GOOGLE";
  readonly dealId: string | null;
  readonly dealTitle: string | null;
  readonly companyId: string | null;
  readonly companyName: string | null;
  readonly contactId: string | null;
  readonly contactName: string | null;
  readonly reminders: readonly ScheduleReminder[];
  readonly createdAt: string;
  readonly updatedAt: string;
  readonly deletedAt: string | null;
  readonly permanentDeleteAt: string | null;
};

type ScheduleReminder = {
  readonly id: string;
  readonly channel: string;
  readonly remindAt: string;
  readonly sentAt: string | null;
  readonly status: "PENDING" | "SENT" | "FAILED" | "READ" | "CANCELED";
  readonly createdAt: string;
  readonly updatedAt: string;
};

type MeetingNote = {
  readonly id: string;
  readonly meetingDate: string | null;
  readonly companyName: string | null;
  readonly contactName: string | null;
  readonly department: string | null;
  readonly productName: string | null;
  readonly stageText: string | null;
  readonly details: string;
  readonly nextPlan: string | null;
  readonly requiredAction: string | null;
  readonly dealId: string | null;
  readonly dealTitle: string | null;
  readonly createdAt: string;
  readonly updatedAt: string;
  readonly deletedAt: string | null;
  readonly permanentDeleteAt: string | null;
};

type CreateCompanyBody = {
  readonly name?: string;
  readonly industry?: string;
  readonly region?: string;
  readonly initialMemo?: string;
  readonly tags?: readonly string[];
};

type CreateContactBody = {
  readonly name?: string;
  readonly companyId?: string;
  readonly department?: string;
  readonly position?: string;
  readonly phone?: string;
  readonly email?: string;
  readonly initialMemo?: string;
};

type CreateProductBody = {
  readonly name?: string;
  readonly category?: string;
  readonly unitPrice?: number;
  readonly currency?: string;
  readonly description?: string;
  readonly initialMemo?: string;
};

type CreateDealBody = {
  readonly title?: string;
  readonly companyId?: string;
  readonly contactId?: string;
  readonly amount?: number;
  readonly currency?: string;
  readonly stage?: DealStage;
  readonly likelihoodStatus?: DealLikelihoodStatus;
  readonly likelihoodPercent?: number;
  readonly expectedCloseDate?: string;
  readonly nextActionText?: string;
  readonly nextActionDueAt?: string;
  readonly productIds?: readonly string[];
  readonly initialMemo?: string;
};

type ChangeDealStageBody = {
  readonly stage?: DealStage;
};

type CreateScheduleBody = {
  readonly title?: string;
  readonly startAt?: string;
  readonly endAt?: string;
  readonly allDay?: boolean;
  readonly location?: string;
  readonly dealId?: string;
  readonly companyId?: string;
  readonly contactId?: string;
  readonly memo?: string;
  readonly reminderMinutes?: readonly number[];
};

type CreateMeetingNoteBody = {
  readonly rawText?: string;
  readonly meetingDate?: string;
  readonly companyName?: string;
  readonly contactName?: string;
  readonly department?: string;
  readonly productName?: string;
  readonly stageText?: string;
  readonly details?: string;
  readonly nextPlan?: string;
  readonly requiredAction?: string;
};

type LinkMeetingNoteBody = {
  readonly dealId?: string;
  readonly activityTitle?: string;
};

type SmokeStore = {
  companies: Company[];
  contacts: Contact[];
  products: Product[];
  deals: Deal[];
  dealProductIds: Map<string, readonly string[]>;
  dealActivities: DealActivity[];
  schedules: Schedule[];
  meetingNotes: MeetingNote[];
  meetingNoteRawText: Map<string, string>;
  sequence: number;
};

type ApiRequestRecord = {
  readonly method: string;
  readonly path: string;
  readonly authorization: string | null;
};

test.describe("User Web smoke E2E", () => {
  test("mock login부터 회의록 저장까지 핵심 업무 흐름이 이어진다", async ({
    page,
  }) => {
    const api = await setupUserWebApiMocks(page);

    await test.step("로그인 보호 라우트와 mock login", async () => {
      await page.goto("/companies");
      await expect(page).toHaveURL(/\/login$/);
      await page.getByRole("button", { name: "계속" }).click();
      await expect(page).toHaveURL(/\/companies$/);
      await expect(
        page.getByRole("heading", { exact: true, name: "회사" })
      ).toBeVisible();
    });

    await test.step("회사 생성", async () => {
      await page.getByRole("button", { name: "회사 추가" }).first().click();
      const dialog = getDialog(page, "회사 빠른 등록");
      await expect(dialog).toBeVisible();
      await dialog.getByLabel("회사명").fill(COMPANY_NAME);
      await dialog.getByLabel("분야").fill("B2C SaaS");
      await dialog.getByLabel("지역").fill("서울");
      await dialog.getByLabel("태그").fill("smoke, mvp");
      await dialog.getByLabel("첫 메모").fill("G34 smoke 회사 fixture");
      await dialog.getByRole("button", { name: "저장" }).click();
      await expect(dialog).toBeHidden();
      await expect(
        page.getByText(`${COMPANY_NAME} 회사가 추가되었습니다.`)
      ).toBeVisible();
      await expect(page.getByRole("link", { name: COMPANY_NAME })).toBeVisible();
    });

    await test.step("담당자 생성", async () => {
      await goToNav(page, "담당자");
      await expect(
        page.getByRole("heading", { exact: true, name: "담당자" })
      ).toBeVisible();
      await page.getByRole("button", { name: "담당자 추가" }).first().click();
      const dialog = getDialog(page, "담당자 빠른 등록");
      await expect(dialog).toBeVisible();
      await dialog.getByLabel("이름").fill(CONTACT_NAME);
      await dialog.getByLabel("회사").fill(COMPANY_NAME);
      await dialog.getByRole("button", { name: new RegExp(COMPANY_NAME) }).click();
      await dialog.getByLabel("부서").fill("구매팀");
      await dialog.getByLabel("직책").fill("팀장");
      await dialog.getByLabel("전화번호").fill("010-1234-5678");
      await dialog.getByLabel("이메일").fill("smoke@example.com");
      await dialog.getByLabel("첫 메모").fill("G34 smoke 담당자 fixture");
      await dialog.getByRole("button", { name: "저장" }).click();
      await expect(dialog).toBeHidden();
      await expect(
        page.getByText(`${CONTACT_NAME} 담당자가 추가되었습니다.`)
      ).toBeVisible();
      await expect(page.getByRole("link", { name: CONTACT_NAME })).toBeVisible();
    });

    await test.step("제품 생성", async () => {
      await goToNav(page, "제품");
      await expect(
        page.getByRole("heading", { exact: true, name: "제품" })
      ).toBeVisible();
      await page.getByRole("button", { name: "제품 추가" }).first().click();
      const dialog = getDialog(page, "제품 빠른 등록");
      await expect(dialog).toBeVisible();
      await dialog.getByLabel("제품명").fill(PRODUCT_NAME);
      await dialog.getByLabel("분류").fill("Starter");
      await dialog.getByLabel("단가").fill("390000");
      await dialog.getByLabel("통화").fill("KRW");
      await dialog.getByLabel("설명").fill("MVP starter smoke 상품");
      await dialog.getByLabel("첫 메모").fill("G34 smoke 제품 fixture");
      await dialog.getByRole("button", { name: "저장" }).click();
      await expect(dialog).toBeHidden();
      await expect(
        page.getByText(`${PRODUCT_NAME} 제품이 추가되었습니다.`)
      ).toBeVisible();
      await expect(page.getByRole("link", { name: PRODUCT_NAME })).toBeVisible();
    });

    await test.step("딜 생성", async () => {
      await goToNav(page, "파이프라인");
      await expect(
        page.getByRole("heading", { name: "딜 파이프라인" })
      ).toBeVisible();
      await page.getByRole("button", { name: "딜 추가" }).first().click();
      const dialog = getDialog(page, "딜 빠른 등록");
      await expect(dialog).toBeVisible();
      await dialog.getByLabel("딜명").fill(DEAL_TITLE);
      await dialog.getByLabel("금액").fill("1200000");
      await dialog.getByLabel("회사").fill(COMPANY_NAME);
      await dialog.getByRole("button", { name: new RegExp(COMPANY_NAME) }).first().click();
      await dialog.getByLabel("담당자").fill(CONTACT_NAME);
      await dialog.getByRole("button", { name: new RegExp(CONTACT_NAME) }).first().click();
      await dialog.getByLabel("제품").fill(PRODUCT_NAME);
      await dialog.getByRole("button", { name: new RegExp(PRODUCT_NAME) }).first().click();
      await dialog.getByLabel("다음 행동", { exact: true }).fill("도입 제안서 발송");
      await dialog.getByRole("button", { name: "저장" }).click();
      await expect(dialog).toBeHidden();
      await expect(page.getByText(`${DEAL_TITLE} 딜이 추가되었습니다.`)).toBeVisible();
      await expect(page.getByText(DEAL_TITLE).first()).toBeVisible();
    });

    await test.step("딜 단계 변경", async () => {
      await page.getByLabel("딜 단계 변경").first().selectOption("IN_DISCUSSION");
      await expect(page.getByText(`${DEAL_TITLE} 단계가 변경되었습니다.`)).toBeVisible();
      await expect(page.getByLabel("딜 단계 변경").first()).toHaveValue(
        "IN_DISCUSSION"
      );
    });

    await test.step("일정 생성", async () => {
      await goToNav(page, "일정");
      await expect(
        page.getByRole("heading", { exact: true, name: "일정" })
      ).toBeVisible();
      await page.getByRole("button", { name: "일정 생성" }).first().click();
      const dialog = getDialog(page, "일정 생성");
      await expect(dialog).toBeVisible();
      await dialog.getByLabel("제목").fill(SCHEDULE_TITLE);
      await dialog.getByLabel("장소").fill("온라인");
      await dialog.getByLabel("딜").fill(DEAL_TITLE);
      await dialog.getByRole("button", { name: new RegExp(DEAL_TITLE) }).click();
      await dialog.getByLabel("메모").fill("G34 smoke 일정 fixture");
      await dialog.getByRole("button", { name: "저장" }).click();
      await expect(dialog).toBeHidden();
      await expect(
        page.getByText(`${SCHEDULE_TITLE} 일정이 생성되었습니다.`)
      ).toBeVisible();
      await expect(page.getByText(SCHEDULE_TITLE).first()).toBeVisible();
    });

    await test.step("회의록 저장과 딜 연결", async () => {
      await goToNav(page, "회의록");
      await expect(
        page.getByRole("heading", { exact: true, name: "회의록" })
      ).toBeVisible();
      await page.getByRole("link", { name: "AI 회의록 작성" }).first().click();
      await expect(
        page.getByRole("heading", { name: "AI 회의록 작성" })
      ).toBeVisible();
      await page
        .getByPlaceholder("회의 내용을 그대로 붙여넣거나 간단히 메모하세요.")
        .fill("고객은 MVP 도입을 검토하고 다음 주 제안서를 요청했다.");
      await page.getByLabel("회사").fill(COMPANY_NAME);
      await page.getByLabel("담당자").fill(CONTACT_NAME);
      await page.getByLabel("부서").fill("구매팀");
      await page.getByLabel("품목").fill(PRODUCT_NAME);
      await page.getByLabel("진행단계").fill("논의 중");
      await page.getByLabel("상세내용").fill(MEETING_DETAILS);
      await page.getByLabel("향후계획").fill("제안서 발송 후 예산 확인");
      await page.getByLabel("필요액션").fill("제안서와 견적서 준비");
      await page.getByLabel("연결할 딜").fill(DEAL_TITLE);
      await page.getByRole("button", { name: new RegExp(DEAL_TITLE) }).click();
      await page.getByRole("button", { name: "저장" }).click();
      await expect(page).toHaveURL(/\/meeting-notes\/meeting-note-/);
      await expect(
        page.getByText("회의록 저장과 딜 연결이 완료되었습니다.")
      ).toBeVisible();
      await expect(page.getByRole("heading", { name: "회의록 상세" })).toBeVisible();
    });

    expect(api.unauthorizedRequests()).toEqual([]);
  });
});

async function setupUserWebApiMocks(page: Page) {
  const store = createStore();
  const requests: ApiRequestRecord[] = [];

  await page.route(isBackendApiRequest, async (route) => {
    const request = route.request();
    const method = request.method();
    const url = new URL(request.url());

    if (method === "OPTIONS") {
      await fulfillJson(route, null, 204);
      return;
    }

    requests.push({
      method,
      path: `${url.pathname}${url.search}`,
      authorization: request.headers().authorization ?? null,
    });

    const body = await handleApiRequest(store, route, method, url);
    await fulfillJson(route, body);
  });

  return {
    unauthorizedRequests: () =>
      requests.filter((request) => request.authorization !== MOCK_ACCESS_TOKEN),
  };
}

function isBackendApiRequest(url: URL) {
  return url.pathname.startsWith("/api/");
}

async function handleApiRequest(
  store: SmokeStore,
  route: Route,
  method: string,
  url: URL
) {
  const path = url.pathname;

  if (path === "/api/search" && method === "GET") {
    return { groups: [] };
  }

  if (path === "/api/companies" && method === "GET") {
    return paginated(filterCompanies(store.companies, url), url);
  }

  if (path === "/api/companies" && method === "POST") {
    const input = await readBody<CreateCompanyBody>(route);
    const company = createCompany(store, input);
    store.companies.push(company);
    return company;
  }

  if (path === "/api/contacts" && method === "GET") {
    return paginated(filterContacts(store.contacts, url), url);
  }

  if (path === "/api/contacts" && method === "POST") {
    const input = await readBody<CreateContactBody>(route);
    const contact = createContact(store, input);
    store.contacts.push(contact);
    return contact;
  }

  if (path === "/api/products" && method === "GET") {
    return paginated(filterProducts(store.products, url), url);
  }

  if (path === "/api/products" && method === "POST") {
    const input = await readBody<CreateProductBody>(route);
    const product = createProduct(store, input);
    store.products.push(product);
    return product;
  }

  if (path === "/api/deals" && method === "GET") {
    const deals = filterDeals(store.deals, url);

    return {
      ...paginated(deals, url),
      stageSummary: toStageSummary(store.deals),
    };
  }

  if (path === "/api/deals" && method === "POST") {
    const input = await readBody<CreateDealBody>(route);
    const deal = createDeal(store, input);
    store.deals.push(deal);
    store.dealProductIds.set(deal.id, input.productIds ?? []);
    store.dealActivities.push(createDealActivity(store, deal.id, "딜 생성"));
    return deal;
  }

  const dealStageMatch = path.match(/^\/api\/deals\/([^/]+)\/stage$/);

  if (dealStageMatch && method === "PATCH") {
    const dealId = decodeURIComponent(dealStageMatch[1] ?? "");
    const input = await readBody<ChangeDealStageBody>(route);
    const deal = requireDeal(store, dealId);
    const updated = { ...deal, stage: input.stage ?? deal.stage, updatedAt: now() };
    replaceDeal(store, updated);
    store.dealActivities.push(
      createDealActivity(store, updated.id, `단계 변경: ${formatStage(updated.stage)}`)
    );
    return updated;
  }

  const dealActivitiesMatch = path.match(/^\/api\/deals\/([^/]+)\/activities$/);

  if (dealActivitiesMatch && method === "GET") {
    const dealId = decodeURIComponent(dealActivitiesMatch[1] ?? "");
    return paginated(
      store.dealActivities.filter((activity) => activity.dealId === dealId),
      url
    );
  }

  const dealDetailMatch = path.match(/^\/api\/deals\/([^/]+)$/);

  if (dealDetailMatch && method === "GET") {
    const dealId = decodeURIComponent(dealDetailMatch[1] ?? "");
    const deal = requireDeal(store, dealId);

    return {
      deal,
      products: productsForDeal(store, deal.id),
      activities: store.dealActivities.filter((activity) => activity.dealId === deal.id),
      memos: [],
      schedulesSummary: { totalCount: 0, upcomingCount: 0 },
      meetingNotesSummary: { totalCount: 0, latestMeetingAt: null },
    };
  }

  if (path === "/api/schedules" && method === "GET") {
    return {
      rangeStart: url.searchParams.get("from") ?? "",
      rangeEnd: url.searchParams.get("to") ?? "",
      items: store.schedules,
    };
  }

  if (path === "/api/schedules" && method === "POST") {
    const input = await readBody<CreateScheduleBody>(route);
    const schedule = createSchedule(store, input);
    store.schedules.push(schedule);
    return schedule;
  }

  const scheduleDetailMatch = path.match(/^\/api\/schedules\/([^/]+)$/);

  if (scheduleDetailMatch && method === "GET") {
    const scheduleId = decodeURIComponent(scheduleDetailMatch[1] ?? "");
    const schedule = requireSchedule(store, scheduleId);

    return {
      schedule,
      deal: schedule.dealId ? { id: schedule.dealId, title: schedule.dealTitle ?? "" } : null,
      company: schedule.companyId
        ? { id: schedule.companyId, name: schedule.companyName ?? "" }
        : null,
      contact: schedule.contactId
        ? { id: schedule.contactId, name: schedule.contactName ?? "" }
        : null,
      reminders: schedule.reminders,
    };
  }

  if (path === "/api/meeting-notes" && method === "GET") {
    return paginated(filterMeetingNotes(store.meetingNotes, url), url);
  }

  if (path === "/api/meeting-notes" && method === "POST") {
    const input = await readBody<CreateMeetingNoteBody>(route);
    const meetingNote = createMeetingNote(store, input);
    store.meetingNotes.push(meetingNote);
    store.meetingNoteRawText.set(meetingNote.id, input.rawText ?? "");
    return meetingNote;
  }

  const meetingNoteLinkMatch = path.match(/^\/api\/meeting-notes\/([^/]+)\/link-deal$/);

  if (meetingNoteLinkMatch && method === "POST") {
    const meetingNoteId = decodeURIComponent(meetingNoteLinkMatch[1] ?? "");
    const input = await readBody<LinkMeetingNoteBody>(route);
    const meetingNote = requireMeetingNote(store, meetingNoteId);
    const deal = input.dealId ? requireDeal(store, input.dealId) : null;
    const linked = {
      ...meetingNote,
      dealId: deal?.id ?? null,
      dealTitle: deal?.title ?? null,
      updatedAt: now(),
    };
    replaceMeetingNote(store, linked);

    if (deal) {
      store.dealActivities.push(
        createDealActivity(store, deal.id, input.activityTitle ?? "회의록 연결")
      );
    }

    return linked;
  }

  const meetingNoteDetailMatch = path.match(/^\/api\/meeting-notes\/([^/]+)$/);

  if (meetingNoteDetailMatch && method === "GET") {
    const meetingNoteId = decodeURIComponent(meetingNoteDetailMatch[1] ?? "");
    const meetingNote = requireMeetingNote(store, meetingNoteId);

    return {
      meetingNote,
      deal: meetingNote.dealId
        ? { id: meetingNote.dealId, title: meetingNote.dealTitle ?? "" }
        : null,
      rawText: store.meetingNoteRawText.get(meetingNote.id) ?? "",
    };
  }

  return {
    error: "MockRouteNotFound",
    message: `${method} ${path} mock이 없습니다.`,
  };
}

function createStore(): SmokeStore {
  return {
    companies: [],
    contacts: [],
    products: [],
    deals: [],
    dealProductIds: new Map(),
    dealActivities: [],
    schedules: [],
    meetingNotes: [],
    meetingNoteRawText: new Map(),
    sequence: 1,
  };
}

function createCompany(store: SmokeStore, input: CreateCompanyBody): Company {
  const id = nextId(store, "company");
  const timestamp = now();

  return {
    id,
    name: input.name ?? COMPANY_NAME,
    industry: input.industry ?? null,
    region: input.region ?? null,
    address: null,
    website: null,
    description: null,
    tags: (input.tags ?? []).map((name, index) => ({
      id: `${id}-tag-${index + 1}`,
      name,
      color: null,
    })),
    hasMemo: Boolean(input.initialMemo),
    memoCount: input.initialMemo ? 1 : 0,
    latestMemoAt: input.initialMemo ? timestamp : null,
    contactCount: 0,
    dealCount: 0,
    productCount: 0,
    createdAt: timestamp,
    updatedAt: timestamp,
    deletedAt: null,
    permanentDeleteAt: null,
  };
}

function createContact(store: SmokeStore, input: CreateContactBody): Contact {
  const id = nextId(store, "contact");
  const timestamp = now();
  const company = input.companyId
    ? store.companies.find((item) => item.id === input.companyId)
    : null;

  return {
    id,
    name: input.name ?? CONTACT_NAME,
    companyId: company?.id ?? null,
    companyName: company?.name ?? null,
    department: input.department ?? null,
    position: input.position ?? null,
    phone: input.phone ?? null,
    email: input.email ?? null,
    address: null,
    hasMemo: Boolean(input.initialMemo),
    memoCount: input.initialMemo ? 1 : 0,
    latestMemoAt: input.initialMemo ? timestamp : null,
    createdAt: timestamp,
    updatedAt: timestamp,
    deletedAt: null,
    permanentDeleteAt: null,
  };
}

function createProduct(store: SmokeStore, input: CreateProductBody): Product {
  const id = nextId(store, "product");
  const timestamp = now();

  return {
    id,
    name: input.name ?? PRODUCT_NAME,
    category: input.category ?? null,
    unitPrice: input.unitPrice ?? null,
    currency: input.currency ?? "KRW",
    description: input.description ?? null,
    connectionCount: 0,
    hasMemo: Boolean(input.initialMemo),
    memoCount: input.initialMemo ? 1 : 0,
    latestMemoAt: input.initialMemo ? timestamp : null,
    createdAt: timestamp,
    updatedAt: timestamp,
    deletedAt: null,
    permanentDeleteAt: null,
  };
}

function createDeal(store: SmokeStore, input: CreateDealBody): Deal {
  const id = nextId(store, "deal");
  const timestamp = now();
  const company = input.companyId
    ? store.companies.find((item) => item.id === input.companyId)
    : null;
  const contact = input.contactId
    ? store.contacts.find((item) => item.id === input.contactId)
    : null;

  return {
    id,
    title: input.title ?? DEAL_TITLE,
    companyId: company?.id ?? null,
    companyName: company?.name ?? null,
    contactId: contact?.id ?? null,
    contactName: contact?.name ?? null,
    amount: input.amount ?? 0,
    currency: input.currency ?? "KRW",
    stage: input.stage ?? "INITIAL_CONTACT",
    likelihoodStatus: input.likelihoodStatus ?? "NEUTRAL",
    likelihoodPercent: input.likelihoodPercent ?? null,
    expectedCloseDate: input.expectedCloseDate ?? null,
    nextActionText: input.nextActionText ?? null,
    nextActionDueAt: input.nextActionDueAt ?? null,
    nextActionStatus: input.nextActionDueAt ? "SCHEDULED" : "NONE",
    hasMemo: Boolean(input.initialMemo),
    memoCount: input.initialMemo ? 1 : 0,
    latestMemoAt: input.initialMemo ? timestamp : null,
    createdAt: timestamp,
    updatedAt: timestamp,
    deletedAt: null,
    permanentDeleteAt: null,
  };
}

function createSchedule(store: SmokeStore, input: CreateScheduleBody): Schedule {
  const id = nextId(store, "schedule");
  const timestamp = now();
  const deal = input.dealId ? store.deals.find((item) => item.id === input.dealId) : null;
  const company = input.companyId
    ? store.companies.find((item) => item.id === input.companyId)
    : deal?.companyId
      ? store.companies.find((item) => item.id === deal.companyId)
      : null;
  const contact = input.contactId
    ? store.contacts.find((item) => item.id === input.contactId)
    : deal?.contactId
      ? store.contacts.find((item) => item.id === deal.contactId)
      : null;
  const startAt = input.startAt ?? timestamp;
  const endAt = input.endAt ?? new Date(new Date(startAt).getTime() + 60 * 60_000).toISOString();

  return {
    id,
    title: input.title ?? SCHEDULE_TITLE,
    startAt,
    endAt,
    allDay: input.allDay ?? false,
    location: input.location ?? null,
    memo: input.memo ?? null,
    source: "INTERNAL",
    dealId: deal?.id ?? null,
    dealTitle: deal?.title ?? null,
    companyId: company?.id ?? null,
    companyName: company?.name ?? null,
    contactId: contact?.id ?? null,
    contactName: contact?.name ?? null,
    reminders: toReminders(id, startAt, input.reminderMinutes ?? []),
    createdAt: timestamp,
    updatedAt: timestamp,
    deletedAt: null,
    permanentDeleteAt: null,
  };
}

function createMeetingNote(
  store: SmokeStore,
  input: CreateMeetingNoteBody
): MeetingNote {
  const id = nextId(store, "meeting-note");
  const timestamp = now();

  return {
    id,
    meetingDate: input.meetingDate ?? timestamp,
    companyName: input.companyName ?? null,
    contactName: input.contactName ?? null,
    department: input.department ?? null,
    productName: input.productName ?? null,
    stageText: input.stageText ?? null,
    details: input.details ?? MEETING_DETAILS,
    nextPlan: input.nextPlan ?? null,
    requiredAction: input.requiredAction ?? null,
    dealId: null,
    dealTitle: null,
    createdAt: timestamp,
    updatedAt: timestamp,
    deletedAt: null,
    permanentDeleteAt: null,
  };
}

function createDealActivity(
  store: SmokeStore,
  dealId: string,
  title: string
): DealActivity {
  const timestamp = now();

  return {
    id: nextId(store, "activity"),
    dealId,
    typeId: "activity-type-system",
    typeName: "시스템",
    occurredAt: timestamp,
    title,
    content: null,
    isAutoGenerated: true,
    createdAt: timestamp,
    updatedAt: timestamp,
    deletedAt: null,
    permanentDeleteAt: null,
  };
}

function filterCompanies(companies: readonly Company[], url: URL) {
  const search = url.searchParams.get("search");

  return companies.filter((company) =>
    matchesSearch([company.name, company.industry, company.region], search)
  );
}

function filterContacts(contacts: readonly Contact[], url: URL) {
  const search = url.searchParams.get("search");
  const companyId = url.searchParams.get("companyId");

  return contacts.filter(
    (contact) =>
      (!companyId || contact.companyId === companyId) &&
      matchesSearch(
        [contact.name, contact.companyName, contact.phone, contact.email],
        search
      )
  );
}

function filterProducts(products: readonly Product[], url: URL) {
  const search = url.searchParams.get("search");
  const category = url.searchParams.get("category");

  return products.filter(
    (product) =>
      (!category || product.category === category) &&
      matchesSearch([product.name, product.category, product.description], search)
  );
}

function filterDeals(deals: readonly Deal[], url: URL) {
  const search = url.searchParams.get("search");
  const stage = url.searchParams.get("stage");

  return deals.filter(
    (deal) =>
      (!stage || deal.stage === stage) &&
      matchesSearch([deal.title, deal.companyName, deal.contactName], search)
  );
}

function filterMeetingNotes(meetingNotes: readonly MeetingNote[], url: URL) {
  const search = url.searchParams.get("search");
  const dealId = url.searchParams.get("dealId");

  return meetingNotes.filter(
    (meetingNote) =>
      (!dealId || meetingNote.dealId === dealId) &&
      matchesSearch(
        [
          meetingNote.companyName,
          meetingNote.contactName,
          meetingNote.productName,
          meetingNote.details,
        ],
        search
      )
  );
}

function productsForDeal(store: SmokeStore, dealId: string) {
  const productIds = store.dealProductIds.get(dealId) ?? [];

  return store.products.filter((product) => productIds.includes(product.id));
}

function toStageSummary(deals: readonly Deal[]) {
  const summary: Record<DealStage, number> = {
    INITIAL_CONTACT: 0,
    IN_DISCUSSION: 0,
    WON: 0,
    LOST: 0,
  };

  for (const deal of deals) {
    summary[deal.stage] += 1;
  }

  return summary;
}

function toReminders(
  scheduleId: string,
  startAt: string,
  minutes: readonly number[]
): ScheduleReminder[] {
  const startAtMs = new Date(startAt).getTime();

  return minutes.map((minute) => ({
    id: `${scheduleId}-reminder-${minute}`,
    channel: "browser",
    remindAt: new Date(startAtMs - minute * 60_000).toISOString(),
    sentAt: null,
    status: "PENDING",
    createdAt: now(),
    updatedAt: now(),
  }));
}

function matchesSearch(
  fields: readonly (string | null | undefined)[],
  search: string | null
) {
  const normalized = search?.trim().toLowerCase() ?? "";

  if (!normalized) {
    return true;
  }

  return fields.some((field) => field?.toLowerCase().includes(normalized));
}

function replaceDeal(store: SmokeStore, deal: Deal) {
  store.deals = store.deals.map((item) => (item.id === deal.id ? deal : item));
}

function replaceMeetingNote(store: SmokeStore, meetingNote: MeetingNote) {
  store.meetingNotes = store.meetingNotes.map((item) =>
    item.id === meetingNote.id ? meetingNote : item
  );
}

function requireDeal(store: SmokeStore, dealId: string) {
  const deal = store.deals.find((item) => item.id === dealId);

  if (!deal) {
    throw new Error(`Deal not found: ${dealId}`);
  }

  return deal;
}

function requireSchedule(store: SmokeStore, scheduleId: string) {
  const schedule = store.schedules.find((item) => item.id === scheduleId);

  if (!schedule) {
    throw new Error(`Schedule not found: ${scheduleId}`);
  }

  return schedule;
}

function requireMeetingNote(store: SmokeStore, meetingNoteId: string) {
  const meetingNote = store.meetingNotes.find((item) => item.id === meetingNoteId);

  if (!meetingNote) {
    throw new Error(`Meeting note not found: ${meetingNoteId}`);
  }

  return meetingNote;
}

function paginated<TItem>(items: readonly TItem[], url: URL) {
  const page = Math.max(1, Number(url.searchParams.get("page") ?? "1"));
  const pageSize = Math.max(1, Number(url.searchParams.get("pageSize") ?? "10"));
  const start = (page - 1) * pageSize;
  const pagedItems = items.slice(start, start + pageSize);

  return {
    items: pagedItems,
    page,
    pageSize,
    totalCount: items.length,
    hasNext: start + pageSize < items.length,
  };
}

async function readBody<TBody>(route: Route): Promise<TBody> {
  const postData = route.request().postData();

  if (!postData) {
    return {} as TBody;
  }

  return JSON.parse(postData) as TBody;
}

async function fulfillJson(route: Route, body: unknown, status = 200) {
  await route.fulfill({
    body: status === 204 ? undefined : JSON.stringify(body),
    contentType: "application/json",
    headers: {
      "access-control-allow-headers": "authorization, content-type",
      "access-control-allow-methods": "GET, POST, PATCH, DELETE, OPTIONS",
      "access-control-allow-origin": "*",
    },
    status,
  });
}

function nextId(store: SmokeStore, prefix: string) {
  const id = `${prefix}-${store.sequence}`;
  store.sequence += 1;

  return id;
}

function now() {
  return "2026-06-07T09:00:00.000Z";
}

function formatStage(stage: DealStage) {
  const labels: Record<DealStage, string> = {
    INITIAL_CONTACT: "초기 접촉",
    IN_DISCUSSION: "논의 중",
    WON: "수주",
    LOST: "실주",
  };

  return labels[stage];
}

function getDialog(page: Page, title: string) {
  return page.locator('[role="dialog"]').filter({ hasText: title });
}

async function goToNav(page: Page, name: string) {
  await page.getByRole("link", { name }).first().click();
}
