DROP TABLE IF EXISTS "DealActivity" CASCADE;
DROP TABLE IF EXISTS "DealFollowingActionLog" CASCADE;
DROP TABLE IF EXISTS "DealMemoLog" CASCADE;
DROP TABLE IF EXISTS "DealProduct" CASCADE;
DROP TABLE IF EXISTS "DealContact" CASCADE;
DROP TABLE IF EXISTS "DealCompany" CASCADE;
DROP TABLE IF EXISTS "Deal" CASCADE;

DROP TABLE IF EXISTS "ProductUserPrivateMemoLog" CASCADE;
DROP TABLE IF EXISTS "ProductMemoLog" CASCADE;
DROP TABLE IF EXISTS "Product" CASCADE;
DROP TABLE IF EXISTS "ProductCategory" CASCADE;
DROP TABLE IF EXISTS "ProductStatus" CASCADE;

DROP TABLE IF EXISTS "ContactUserPrivateMemoLog" CASCADE;
DROP TABLE IF EXISTS "ContactMemoLog" CASCADE;
DROP TABLE IF EXISTS "Contact" CASCADE;
DROP TABLE IF EXISTS "ContactDepartment" CASCADE;
DROP TABLE IF EXISTS "ContactJobGrade" CASCADE;

DROP TABLE IF EXISTS "ProductAnalyticsEvent" CASCADE;
DROP TABLE IF EXISTS "UserActivationSnapshot" CASCADE;
DROP TABLE IF EXISTS "RetentionCohortSnapshot" CASCADE;

DROP TYPE IF EXISTS "DealActivityType" CASCADE;
DROP TYPE IF EXISTS "DealActivitySourceType" CASCADE;
DROP TYPE IF EXISTS "ProductAnalyticsEventSource" CASCADE;
DROP TYPE IF EXISTS "UserActivationStatus" CASCADE;
DROP TYPE IF EXISTS "ProductAnalyticsTargetType" CASCADE;
DROP TYPE IF EXISTS "AiSuggestionPriority" CASCADE;
