import {
  DealLikelihoodStatus as PrismaDealLikelihoodStatus,
  DealStage as PrismaDealStage,
  NextActionStatus as PrismaNextActionStatus,
  PersonalMemoTargetType,
  Prisma,
  ProductConnectionTargetType,
  ProductConnectionType,
} from "@prisma/client";
import type { MemoSummaryRecord } from "@/modules/company/application/ports/company.repository";
import {
  type ChangeDealStageInput,
  type CompleteDealNextActionInput,
  type CreateDealActivityInput,
  type CreateDealInput,
  type DealActivityRecord,
  type DealDetailRecord,
  type DealListResult,
  type DealMeetingNotesSummaryRecord,
  type DealMemoRecord,
  type DealProductRecord,
  DealRepository,
  type DealRecord,
  type DealSchedulesSummaryRecord,
  type DeleteResultRecord,
  type ListDealActivitiesInput,
  type ListDealsInput,
  type PaginatedResult,
  type SnoozeDealNextActionInput,
  type UpdateDealActivityInput,
  type UpdateDealInput,
  type UpdateDealNextActionInput,
} from "@/modules/deal/application/ports/deal.repository";
import {
  DealActivityNotFoundError,
  DealActivityTypeNotFoundError,
  DealNotFoundError,
  NextActionNotFoundError,
  OwnershipViolationError,
  RelatedEntityNotFoundError,
} from "@/modules/deal/domain/deal.errors";
import type { EncryptionPort } from "@/shared/application/ports/encryption.port";
import {
  DeletedResourceError,
  ValidationDomainError,
} from "@/shared/domain/errors/common.errors";
import { PrismaService } from "@/shared/infrastructure/prisma/prisma.service";

type DealPrismaClient = PrismaService | Prisma.TransactionClient;

type DealRow = {
  readonly id: string;
  readonly userId: string;
  readonly companyId: string | null;
  readonly contactId: string | null;
  readonly title: string;
  readonly amount: Prisma.Decimal;
  readonly currency: string;
  readonly stage: PrismaDealStage;
  readonly likelihoodStatus: PrismaDealLikelihoodStatus;
  readonly likelihoodPercent: number | null;
  readonly nextActionTitle: string | null;
  readonly nextActionDueAt: Date | null;
  readonly nextActionStatus: PrismaNextActionStatus;
  readonly expectedCloseDate: Date | null;
  readonly createdAt: Date;
  readonly updatedAt: Date;
  readonly deletedAt: Date | null;
  readonly permanentDeleteAt: Date | null;
  readonly company?: { readonly name: string } | null;
  readonly contact?: { readonly name: string } | null;
};

type DealActivityRow = {
  readonly id: string;
  readonly dealId: string;
  readonly typeId: string;
  readonly activityDate: Date;
  readonly title: string;
  readonly content: string | null;
  readonly isAutoGenerated: boolean;
  readonly createdAt: Date;
  readonly updatedAt: Date;
  readonly deletedAt: Date | null;
  readonly permanentDeleteAt: Date | null;
  readonly type?: { readonly name: string } | null;
};

type ProductRow = {
  readonly id: string;
  readonly userId: string;
  readonly name: string;
  readonly category: string | null;
  readonly description: string | null;
  readonly unitPrice: Prisma.Decimal | null;
  readonly metadata: Prisma.JsonValue | null;
  readonly createdAt: Date;
  readonly updatedAt: Date;
  readonly deletedAt: Date | null;
  readonly permanentDeleteAt: Date | null;
};

type CompanyRecord = {
  readonly id: string;
  readonly userId: string;
  readonly deletedAt: Date | null;
};

type ContactRecord = {
  readonly id: string;
  readonly userId: string;
  readonly companyId: string | null;
  readonly deletedAt: Date | null;
};

type ResolvedRelations = {
  readonly companyId: string | null;
  readonly contactId: string | null;
};

const DEFAULT_ACTIVITY_TYPE_NAME = "기타 기록";
const STAGE_ACTIVITY_TYPE_NAME = "단계변경";

export class PrismaDealRepository implements DealRepository {
  constructor(
    private readonly prismaService: PrismaService,
    private readonly encryptionPort: EncryptionPort
  ) {}

  async listDeals(input: ListDealsInput): Promise<DealListResult> {
    const where = this.createDealWhere(input);
    const [deals, totalCount, stageSummary] = await Promise.all([
      this.prismaService.deal.findMany({
        where,
        include: {
          company: { select: { name: true } },
          contact: { select: { name: true } },
        },
        orderBy: { updatedAt: "desc" },
        skip: (input.page - 1) * input.pageSize,
        take: input.pageSize,
      }),
      this.prismaService.deal.count({ where }),
      this.getStageSummary(input.userId),
    ]);

    return {
      items: await Promise.all(
        deals.map((deal) => this.mapDealRecord(deal))
      ),
      stageSummary,
      page: input.page,
      pageSize: input.pageSize,
      totalCount,
      hasNext: input.page * input.pageSize < totalCount,
    };
  }

  async createDeal(input: CreateDealInput): Promise<DealRecord> {
    return this.prismaService.$transaction(async (transaction) => {
      const relations = await this.resolveRelations(transaction, input.userId, {
        companyId: input.companyId,
        contactId: input.contactId,
      });
      await this.assertProducts(transaction, input.userId, input.productIds);
      const deal = await transaction.deal.create({
        data: {
          userId: input.userId,
          companyId: relations.companyId,
          contactId: relations.contactId,
          title: input.title,
          amount: input.amount,
          currency: input.currency,
          stage: input.stage,
          likelihoodStatus: input.likelihoodStatus,
          likelihoodPercent: input.likelihoodPercent,
          expectedCloseDate: input.expectedCloseDate,
          nextActionTitle: input.nextActionText,
          nextActionDueAt: input.nextActionDueAt,
          nextActionStatus: this.resolveInitialNextActionStatus(
            input.nextActionText,
            input.nextActionDueAt
          ),
        },
        include: {
          company: { select: { name: true } },
          contact: { select: { name: true } },
        },
      });

      await this.replaceProductConnections(transaction, {
        userId: input.userId,
        dealId: deal.id,
        productIds: input.productIds,
      });

      if (input.initialMemo) {
        const encrypted = await this.encryptionPort.encryptText(input.initialMemo);
        await transaction.personalMemo.create({
          data: {
            userId: input.userId,
            targetType: PersonalMemoTargetType.DEAL,
            targetId: deal.id,
            title: "초기 Memo",
            contentCiphertext: encrypted.ciphertext,
            contentKeyVersion: encrypted.keyVersion,
          },
        });
      }

      await this.createAutoActivity(transaction, {
        userId: input.userId,
        dealId: deal.id,
        typeName: DEFAULT_ACTIVITY_TYPE_NAME,
        occurredAt: deal.createdAt,
        title: "딜 생성",
        content: null,
      });

      return this.mapDealRecord(deal, transaction);
    });
  }

  async getDealDetail(
    userId: string,
    dealId: string
  ): Promise<DealDetailRecord | null> {
    const deal = await this.prismaService.deal.findFirst({
      where: { id: dealId, userId },
      include: {
        company: { select: { name: true } },
        contact: { select: { name: true } },
      },
    });

    if (!deal) {
      return null;
    }

    const [products, activities, memos, schedulesSummary, meetingNotesSummary] =
      await Promise.all([
        this.listDealProducts(userId, dealId),
        this.listRecentActivities(userId, dealId),
        this.listMemos(userId, dealId),
        this.getSchedulesSummary(userId, dealId),
        this.getMeetingNotesSummary(userId, dealId),
      ]);

    return {
      deal: await this.mapDealRecord(deal),
      products,
      activities,
      memos,
      schedulesSummary,
      meetingNotesSummary,
    };
  }

  async updateDeal(input: UpdateDealInput): Promise<DealRecord> {
    return this.prismaService.$transaction(async (transaction) => {
      const existing = await this.assertDealExists(
        input.userId,
        input.dealId,
        "write",
        transaction
      );
      const relations =
        input.companyId !== undefined || input.contactId !== undefined
          ? await this.resolveRelations(transaction, input.userId, {
              companyId:
                input.companyId !== undefined
                  ? input.companyId
                  : existing.companyId,
              contactId:
                input.contactId !== undefined
                  ? input.contactId
                  : existing.contactId,
            })
          : null;

      if (input.productIds !== undefined) {
        await this.assertProducts(transaction, input.userId, input.productIds);
      }

      const data: Prisma.DealUpdateInput = {};

      if (input.title !== undefined) {
        data.title = input.title;
      }

      if (
        relations &&
        (input.companyId !== undefined || input.contactId !== undefined)
      ) {
        data.company = relations?.companyId
          ? { connect: { id: relations.companyId } }
          : { disconnect: true };
      }

      if (input.contactId !== undefined) {
        data.contact = relations?.contactId
          ? { connect: { id: relations.contactId } }
          : { disconnect: true };
      }

      if (input.amount !== undefined) {
        data.amount = input.amount;
      }

      if (input.currency !== undefined) {
        data.currency = input.currency;
      }

      if (input.stage !== undefined) {
        data.stage = input.stage;
      }

      if (input.likelihoodStatus !== undefined) {
        data.likelihoodStatus = input.likelihoodStatus;
      }

      if (input.likelihoodPercent !== undefined) {
        data.likelihoodPercent = input.likelihoodPercent;
      }

      if (input.expectedCloseDate !== undefined) {
        data.expectedCloseDate = input.expectedCloseDate;
      }

      if (input.nextActionText !== undefined) {
        data.nextActionTitle = input.nextActionText;
      }

      if (input.nextActionDueAt !== undefined) {
        data.nextActionDueAt = input.nextActionDueAt;
      }

      if (input.nextActionStatus !== undefined) {
        data.nextActionStatus = input.nextActionStatus;
      } else if (
        input.nextActionText !== undefined ||
        input.nextActionDueAt !== undefined
      ) {
        data.nextActionStatus = this.resolveInitialNextActionStatus(
          input.nextActionText !== undefined
            ? input.nextActionText
            : existing.nextActionTitle,
          input.nextActionDueAt !== undefined
            ? input.nextActionDueAt
            : existing.nextActionDueAt
        );
      }

      const deal = await transaction.deal.update({
        where: { id: input.dealId },
        data,
        include: {
          company: { select: { name: true } },
          contact: { select: { name: true } },
        },
      });

      if (input.productIds !== undefined) {
        await this.replaceProductConnections(transaction, {
          userId: input.userId,
          dealId: deal.id,
          productIds: input.productIds,
        });
      }

      return this.mapDealRecord(deal, transaction);
    });
  }

  async changeDealStage(input: ChangeDealStageInput): Promise<DealRecord> {
    return this.prismaService.$transaction(async (transaction) => {
      const existing = await this.assertDealExists(
        input.userId,
        input.dealId,
        "write",
        transaction
      );

      if (existing.stage === input.stage) {
        return this.mapDealRecord(existing, transaction);
      }

      const deal = await transaction.deal.update({
        where: { id: input.dealId },
        data: { stage: input.stage },
        include: {
          company: { select: { name: true } },
          contact: { select: { name: true } },
        },
      });

      await this.createAutoActivity(transaction, {
        userId: input.userId,
        dealId: input.dealId,
        typeName: STAGE_ACTIVITY_TYPE_NAME,
        occurredAt: input.occurredAt,
        title:
          input.activityTitle ??
          `단계 변경: ${this.toStageLabel(existing.stage)} -> ${this.toStageLabel(input.stage)}`,
        content: input.activityContent,
      });

      return this.mapDealRecord(deal, transaction);
    });
  }

  async updateDealNextAction(
    input: UpdateDealNextActionInput
  ): Promise<DealRecord> {
    const existing = await this.assertDealExists(input.userId, input.dealId, "write");
    const data: Prisma.DealUpdateInput = {};

    if (input.nextActionText !== undefined) {
      data.nextActionTitle = input.nextActionText;
    }

    if (input.nextActionDueAt !== undefined) {
      data.nextActionDueAt = input.nextActionDueAt;
    }

    if (input.nextActionStatus !== undefined) {
      data.nextActionStatus = input.nextActionStatus;
    } else if (
      input.nextActionText !== undefined ||
      input.nextActionDueAt !== undefined
    ) {
      data.nextActionStatus = this.resolveInitialNextActionStatus(
        input.nextActionText !== undefined
          ? input.nextActionText
          : existing.nextActionTitle,
        input.nextActionDueAt !== undefined
          ? input.nextActionDueAt
          : existing.nextActionDueAt
      );
    }

    const deal = await this.prismaService.deal.update({
      where: { id: input.dealId },
      data,
      include: {
        company: { select: { name: true } },
        contact: { select: { name: true } },
      },
    });

    return this.mapDealRecord(deal);
  }

  async completeDealNextAction(
    input: CompleteDealNextActionInput
  ): Promise<DealRecord> {
    return this.prismaService.$transaction(async (transaction) => {
      const existing = await this.assertDealExists(
        input.userId,
        input.dealId,
        "write",
        transaction
      );
      this.assertNextActionExists(existing);
      const deal = await transaction.deal.update({
        where: { id: input.dealId },
        data: { nextActionStatus: "DONE" },
        include: {
          company: { select: { name: true } },
          contact: { select: { name: true } },
        },
      });

      await this.createAutoActivity(transaction, {
        userId: input.userId,
        dealId: input.dealId,
        typeName: DEFAULT_ACTIVITY_TYPE_NAME,
        occurredAt: input.completedAt,
        title: `다음 행동 완료: ${existing.nextActionTitle ?? "이름 없음"}`,
        content: input.activityContent,
      });

      return this.mapDealRecord(deal, transaction);
    });
  }

  async snoozeDealNextAction(
    input: SnoozeDealNextActionInput
  ): Promise<DealRecord> {
    return this.prismaService.$transaction(async (transaction) => {
      const existing = await this.assertDealExists(
        input.userId,
        input.dealId,
        "write",
        transaction
      );
      this.assertNextActionExists(existing);
      const deal = await transaction.deal.update({
        where: { id: input.dealId },
        data: {
          nextActionDueAt: input.nextActionDueAt,
          nextActionStatus: "SCHEDULED",
        },
        include: {
          company: { select: { name: true } },
          contact: { select: { name: true } },
        },
      });

      await this.createAutoActivity(transaction, {
        userId: input.userId,
        dealId: input.dealId,
        typeName: DEFAULT_ACTIVITY_TYPE_NAME,
        occurredAt: new Date(),
        title: `다음 행동 미루기: ${existing.nextActionTitle ?? "이름 없음"}`,
        content: input.reason,
      });

      return this.mapDealRecord(deal, transaction);
    });
  }

  async deleteDeal(
    userId: string,
    dealId: string,
    now: Date,
    permanentDeleteAt: Date
  ): Promise<DeleteResultRecord> {
    const deal = await this.prismaService.deal.findFirst({
      where: { id: dealId, userId },
    });

    if (!deal) {
      throw new DealNotFoundError();
    }

    if (deal.deletedAt) {
      throw new DeletedResourceError("write");
    }

    await this.prismaService.deal.update({
      where: { id: dealId },
      data: { deletedAt: now, permanentDeleteAt },
    });

    return { id: dealId, deletedAt: now, permanentDeleteAt };
  }

  async restoreDeal(userId: string, dealId: string): Promise<DealRecord> {
    const deal = await this.prismaService.deal.findFirst({
      where: { id: dealId, userId },
    });

    if (!deal) {
      throw new DealNotFoundError();
    }

    const restored = await this.prismaService.deal.update({
      where: { id: dealId },
      data: { deletedAt: null, permanentDeleteAt: null },
      include: {
        company: { select: { name: true } },
        contact: { select: { name: true } },
      },
    });

    return this.mapDealRecord(restored);
  }

  async listDealActivities(
    input: ListDealActivitiesInput
  ): Promise<PaginatedResult<DealActivityRecord>> {
    await this.assertDealExists(input.userId, input.dealId, "read");
    const where = {
      userId: input.userId,
      dealId: input.dealId,
      deletedAt: null,
    };
    const [activities, totalCount] = await Promise.all([
      this.prismaService.dealActivity.findMany({
        where,
        include: { type: { select: { name: true } } },
        orderBy: { activityDate: "desc" },
        skip: (input.page - 1) * input.pageSize,
        take: input.pageSize,
      }),
      this.prismaService.dealActivity.count({ where }),
    ]);

    return {
      items: activities.map((activity) =>
        this.mapDealActivityRecord(activity)
      ),
      page: input.page,
      pageSize: input.pageSize,
      totalCount,
      hasNext: input.page * input.pageSize < totalCount,
    };
  }

  async createDealActivity(
    input: CreateDealActivityInput
  ): Promise<DealActivityRecord> {
    await this.assertDealExists(input.userId, input.dealId, "write");
    await this.assertActivityType(input.userId, input.typeId);
    const activity = await this.prismaService.dealActivity.create({
      data: {
        userId: input.userId,
        dealId: input.dealId,
        typeId: input.typeId,
        activityDate: input.occurredAt,
        title: input.title,
        content: input.content,
        isAutoGenerated: false,
      },
      include: { type: { select: { name: true } } },
    });

    return this.mapDealActivityRecord(activity);
  }

  async updateDealActivity(
    input: UpdateDealActivityInput
  ): Promise<DealActivityRecord> {
    const existing = await this.prismaService.dealActivity.findFirst({
      where: {
        id: input.activityId,
        dealId: input.dealId,
        userId: input.userId,
      },
    });

    if (!existing) {
      throw new DealActivityNotFoundError();
    }

    if (existing.deletedAt) {
      throw new DeletedResourceError("write");
    }

    await this.assertDealExists(input.userId, input.dealId, "write");

    if (input.typeId !== undefined) {
      await this.assertActivityType(input.userId, input.typeId);
    }

    const activity = await this.prismaService.dealActivity.update({
      where: { id: input.activityId },
      data: {
        ...(input.typeId !== undefined ? { typeId: input.typeId } : {}),
        ...(input.occurredAt !== undefined
          ? { activityDate: input.occurredAt }
          : {}),
        ...(input.title !== undefined ? { title: input.title } : {}),
        ...(input.content !== undefined ? { content: input.content } : {}),
      },
      include: { type: { select: { name: true } } },
    });

    return this.mapDealActivityRecord(activity);
  }

  async deleteDealActivity(
    userId: string,
    dealId: string,
    activityId: string,
    now: Date,
    permanentDeleteAt: Date
  ): Promise<DeleteResultRecord> {
    await this.assertDealExists(userId, dealId, "write");
    const existing = await this.prismaService.dealActivity.findFirst({
      where: { id: activityId, dealId, userId },
    });

    if (!existing) {
      throw new DealActivityNotFoundError();
    }

    if (existing.deletedAt) {
      throw new DeletedResourceError("write");
    }

    await this.prismaService.dealActivity.update({
      where: { id: activityId },
      data: { deletedAt: now, permanentDeleteAt },
    });

    return { id: activityId, deletedAt: now, permanentDeleteAt };
  }

  private createDealWhere(input: ListDealsInput): Prisma.DealWhereInput {
    return {
      userId: input.userId,
      ...(input.stage ? { stage: input.stage } : {}),
      ...(input.likelihoodStatus
        ? { likelihoodStatus: input.likelihoodStatus }
        : {}),
      ...(input.companyId ? { companyId: input.companyId } : {}),
      ...(input.contactId ? { contactId: input.contactId } : {}),
      ...(input.nextActionStatus
        ? { nextActionStatus: input.nextActionStatus }
        : {}),
      ...(input.includeDeleted ? {} : { deletedAt: null }),
      ...(input.search
        ? {
            OR: [
              { title: { contains: input.search, mode: "insensitive" } },
              {
                company: {
                  name: { contains: input.search, mode: "insensitive" },
                },
              },
              {
                contact: {
                  name: { contains: input.search, mode: "insensitive" },
                },
              },
            ],
          }
        : {}),
    };
  }

  private async resolveRelations(
    client: DealPrismaClient,
    userId: string,
    input: {
      readonly companyId: string | null;
      readonly contactId: string | null;
    }
  ): Promise<ResolvedRelations> {
    const company = input.companyId
      ? await this.assertCompany(client, userId, input.companyId)
      : null;
    const contact = input.contactId
      ? await this.assertContact(client, userId, input.contactId)
      : null;
    const inferredCompanyId = company?.id ?? contact?.companyId ?? null;

    if (company && contact?.companyId && contact.companyId !== company.id) {
      throw new ValidationDomainError("Contact does not belong to the company");
    }

    if (inferredCompanyId && !company) {
      await this.assertCompany(client, userId, inferredCompanyId);
    }

    return {
      companyId: inferredCompanyId,
      contactId: contact?.id ?? null,
    };
  }

  private async assertCompany(
    client: DealPrismaClient,
    userId: string,
    companyId: string
  ): Promise<CompanyRecord> {
    const company = await client.company.findUnique({ where: { id: companyId } });

    if (!company) {
      throw new RelatedEntityNotFoundError();
    }

    if (company.userId !== userId) {
      throw new OwnershipViolationError();
    }

    if (company.deletedAt) {
      throw new DeletedResourceError("write");
    }

    return company;
  }

  private async assertContact(
    client: DealPrismaClient,
    userId: string,
    contactId: string
  ): Promise<ContactRecord> {
    const contact = await client.contact.findUnique({ where: { id: contactId } });

    if (!contact) {
      throw new RelatedEntityNotFoundError();
    }

    if (contact.userId !== userId) {
      throw new OwnershipViolationError();
    }

    if (contact.deletedAt) {
      throw new DeletedResourceError("write");
    }

    return contact;
  }

  private async assertProducts(
    client: DealPrismaClient,
    userId: string,
    productIds: readonly string[]
  ): Promise<void> {
    for (const productId of productIds) {
      const product = await client.product.findUnique({ where: { id: productId } });

      if (!product) {
        throw new RelatedEntityNotFoundError();
      }

      if (product.userId !== userId) {
        throw new OwnershipViolationError();
      }

      if (product.deletedAt) {
        throw new DeletedResourceError("write");
      }
    }
  }

  private async replaceProductConnections(
    client: DealPrismaClient,
    input: {
      readonly userId: string;
      readonly dealId: string;
      readonly productIds: readonly string[];
    }
  ): Promise<void> {
    const activeConnections = await client.productConnection.findMany({
      where: {
        userId: input.userId,
        targetType: ProductConnectionTargetType.DEAL,
        targetId: input.dealId,
        deletedAt: null,
      },
    });
    const nextProductIds = new Set(input.productIds);
    const now = new Date();
    const permanentDeleteAt = new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000);

    for (const connection of activeConnections) {
      if (!nextProductIds.has(connection.productId)) {
        await client.productConnection.update({
          where: { id: connection.id },
          data: { deletedAt: now, permanentDeleteAt },
        });
      }
    }

    const existingProductIds = new Set(
      activeConnections
        .filter((connection) => nextProductIds.has(connection.productId))
        .map((connection) => connection.productId)
    );

    for (const productId of input.productIds) {
      if (!existingProductIds.has(productId)) {
        await client.productConnection.create({
          data: {
            userId: input.userId,
            productId,
            targetType: ProductConnectionTargetType.DEAL,
            targetId: input.dealId,
            connectionType: ProductConnectionType.PROPOSED,
          },
        });
      }
    }
  }

  private async assertDealExists(
    userId: string,
    dealId: string,
    operation: "read" | "write",
    client: DealPrismaClient = this.prismaService
  ): Promise<DealRow> {
    const deal = await client.deal.findFirst({
      where: { id: dealId, userId },
      include: {
        company: { select: { name: true } },
        contact: { select: { name: true } },
      },
    });

    if (!deal) {
      throw new DealNotFoundError();
    }

    if (deal.deletedAt) {
      throw new DeletedResourceError(operation);
    }

    return deal;
  }

  private async assertActivityType(
    userId: string,
    typeId: string,
    client: DealPrismaClient = this.prismaService
  ): Promise<void> {
    const type = await client.dealActivityType.findUnique({ where: { id: typeId } });

    if (!type || (type.userId !== null && type.userId !== userId)) {
      throw new DealActivityTypeNotFoundError();
    }
  }

  private async createAutoActivity(
    client: DealPrismaClient,
    input: {
      readonly userId: string;
      readonly dealId: string;
      readonly typeName: string;
      readonly occurredAt: Date;
      readonly title: string;
      readonly content: string | null;
    }
  ): Promise<void> {
    const typeId = await this.findOrCreateSystemActivityType(
      client,
      input.typeName
    );
    await client.dealActivity.create({
      data: {
        userId: input.userId,
        dealId: input.dealId,
        typeId,
        activityDate: input.occurredAt,
        title: input.title,
        content: input.content,
        isAutoGenerated: true,
      },
    });
  }

  private async findOrCreateSystemActivityType(
    client: DealPrismaClient,
    name: string
  ): Promise<string> {
    const existing = await client.dealActivityType.findFirst({
      where: { userId: null, name },
      orderBy: { createdAt: "asc" },
    });

    if (existing) {
      return existing.id;
    }

    const type = await client.dealActivityType.create({
      data: { name, isSystem: true },
    });

    return type.id;
  }

  private assertNextActionExists(deal: DealRow): void {
    if (!deal.nextActionTitle && !deal.nextActionDueAt) {
      throw new NextActionNotFoundError();
    }
  }

  private async mapDealRecord(
    deal: DealRow,
    client: DealPrismaClient = this.prismaService
  ): Promise<DealRecord> {
    return {
      id: deal.id,
      userId: deal.userId,
      title: deal.title,
      companyId: deal.companyId,
      companyName: deal.company?.name ?? null,
      contactId: deal.contactId,
      contactName: deal.contact?.name ?? null,
      amount: Number(deal.amount),
      currency: deal.currency,
      stage: deal.stage,
      likelihoodStatus: deal.likelihoodStatus,
      likelihoodPercent: deal.likelihoodPercent,
      expectedCloseDate: deal.expectedCloseDate,
      nextActionText: deal.nextActionTitle,
      nextActionDueAt: deal.nextActionDueAt,
      nextActionStatus: deal.nextActionStatus,
      memoSummary: await this.getMemoSummary(client, deal.userId, deal.id),
      createdAt: deal.createdAt,
      updatedAt: deal.updatedAt,
      deletedAt: deal.deletedAt,
      permanentDeleteAt: deal.permanentDeleteAt,
    };
  }

  private mapDealActivityRecord(
    activity: DealActivityRow
  ): DealActivityRecord {
    return {
      id: activity.id,
      dealId: activity.dealId,
      typeId: activity.typeId,
      typeName: activity.type?.name ?? "-",
      occurredAt: activity.activityDate,
      title: activity.title,
      content: activity.content,
      isAutoGenerated: activity.isAutoGenerated,
      createdAt: activity.createdAt,
      updatedAt: activity.updatedAt,
      deletedAt: activity.deletedAt,
      permanentDeleteAt: activity.permanentDeleteAt,
    };
  }

  private async listDealProducts(
    userId: string,
    dealId: string
  ): Promise<DealProductRecord[]> {
    const connections = await this.prismaService.productConnection.findMany({
      where: {
        userId,
        targetType: ProductConnectionTargetType.DEAL,
        targetId: dealId,
        deletedAt: null,
        product: { deletedAt: null },
      },
      include: { product: true },
      orderBy: { createdAt: "desc" },
    });

    return Promise.all(
      connections.map((connection) =>
        this.mapDealProductRecord(connection.product)
      )
    );
  }

  private async mapDealProductRecord(
    product: ProductRow,
    client: DealPrismaClient = this.prismaService
  ): Promise<DealProductRecord> {
    return {
      id: product.id,
      name: product.name,
      category: product.category,
      unitPrice: product.unitPrice ? Number(product.unitPrice) : null,
      currency: this.fromProductMetadata(product.metadata).currency,
      description: product.description,
      connectionCount: await client.productConnection.count({
        where: { userId: product.userId, productId: product.id, deletedAt: null },
      }),
      memoSummary: await this.getProductMemoSummary(
        client,
        product.userId,
        product.id
      ),
      createdAt: product.createdAt,
      updatedAt: product.updatedAt,
      deletedAt: product.deletedAt,
      permanentDeleteAt: product.permanentDeleteAt,
    };
  }

  private async listRecentActivities(
    userId: string,
    dealId: string
  ): Promise<DealActivityRecord[]> {
    const activities = await this.prismaService.dealActivity.findMany({
      where: { userId, dealId, deletedAt: null },
      include: { type: { select: { name: true } } },
      orderBy: { activityDate: "desc" },
      take: 20,
    });

    return activities.map((activity) => this.mapDealActivityRecord(activity));
  }

  private async getStageSummary(
    userId: string
  ): Promise<{
    INITIAL_CONTACT: number;
    IN_DISCUSSION: number;
    WON: number;
    LOST: number;
  }> {
    const rows = await this.prismaService.deal.groupBy({
      by: ["stage"],
      where: { userId, deletedAt: null },
      _count: { _all: true },
    });
    const summary = {
      INITIAL_CONTACT: 0,
      IN_DISCUSSION: 0,
      WON: 0,
      LOST: 0,
    };

    for (const row of rows) {
      summary[row.stage] = row._count._all;
    }

    return summary;
  }

  private async getMemoSummary(
    client: DealPrismaClient,
    userId: string,
    dealId: string
  ): Promise<MemoSummaryRecord> {
    return this.getTargetMemoSummary(
      client,
      userId,
      PersonalMemoTargetType.DEAL,
      dealId
    );
  }

  private async getProductMemoSummary(
    client: DealPrismaClient,
    userId: string,
    productId: string
  ): Promise<MemoSummaryRecord> {
    return this.getTargetMemoSummary(
      client,
      userId,
      PersonalMemoTargetType.PRODUCT,
      productId
    );
  }

  private async getTargetMemoSummary(
    client: DealPrismaClient,
    userId: string,
    targetType: PersonalMemoTargetType,
    targetId: string
  ): Promise<MemoSummaryRecord> {
    const [memoCount, latestMemo] = await Promise.all([
      client.personalMemo.count({
        where: { userId, targetType, targetId, deletedAt: null },
      }),
      client.personalMemo.findFirst({
        where: { userId, targetType, targetId, deletedAt: null },
        orderBy: { memoDate: "desc" },
      }),
    ]);

    return {
      hasMemo: memoCount > 0,
      memoCount,
      latestMemoAt: latestMemo?.memoDate ?? null,
    };
  }

  private async listMemos(userId: string, dealId: string): Promise<DealMemoRecord[]> {
    const memos = await this.prismaService.personalMemo.findMany({
      where: {
        userId,
        targetType: PersonalMemoTargetType.DEAL,
        targetId: dealId,
        deletedAt: null,
      },
      orderBy: { memoDate: "desc" },
      take: 20,
    });

    return Promise.all(
      memos.map(async (memo) => ({
        id: memo.id,
        targetType: "DEAL" as const,
        targetId: memo.targetId,
        memoDate: memo.memoDate,
        title: memo.title,
        content: await this.encryptionPort.decryptText({
          ciphertext: memo.contentCiphertext,
          keyVersion: memo.contentKeyVersion,
        }),
        createdAt: memo.createdAt,
        updatedAt: memo.updatedAt,
        deletedAt: memo.deletedAt,
        permanentDeleteAt: memo.permanentDeleteAt,
      }))
    );
  }

  private async getSchedulesSummary(
    userId: string,
    dealId: string
  ): Promise<DealSchedulesSummaryRecord> {
    const now = new Date();
    const [totalCount, upcomingCount] = await Promise.all([
      this.prismaService.schedule.count({
        where: { userId, dealId, deletedAt: null },
      }),
      this.prismaService.schedule.count({
        where: { userId, dealId, deletedAt: null, startAt: { gte: now } },
      }),
    ]);

    return { totalCount, upcomingCount };
  }

  private async getMeetingNotesSummary(
    userId: string,
    dealId: string
  ): Promise<DealMeetingNotesSummaryRecord> {
    const [totalCount, latestMeeting] = await Promise.all([
      this.prismaService.meetingNote.count({
        where: { userId, dealId, deletedAt: null },
      }),
      this.prismaService.meetingNote.findFirst({
        where: { userId, dealId, deletedAt: null },
        orderBy: { meetingDate: "desc" },
      }),
    ]);

    return {
      totalCount,
      latestMeetingAt: latestMeeting?.meetingDate ?? null,
    };
  }

  private resolveInitialNextActionStatus(
    nextActionText: string | null,
    nextActionDueAt: Date | null
  ): PrismaNextActionStatus {
    return nextActionText || nextActionDueAt ? "SCHEDULED" : "NONE";
  }

  private fromProductMetadata(metadata: Prisma.JsonValue | null): {
    currency: string;
  } {
    if (!metadata || typeof metadata !== "object" || Array.isArray(metadata)) {
      return { currency: "KRW" };
    }

    const value = (metadata as Record<string, unknown>).currency;

    return {
      currency: typeof value === "string" && value.trim() ? value : "KRW",
    };
  }

  private toStageLabel(stage: PrismaDealStage): string {
    const labels: Record<PrismaDealStage, string> = {
      INITIAL_CONTACT: "초기 접촉",
      IN_DISCUSSION: "논의 중",
      WON: "수주",
      LOST: "실패",
    };

    return labels[stage];
  }
}
